# Generated by Django 4.0.3 on 2022-03-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_userauthentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthentication',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='authentication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authenticate.userauthentication'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_medium',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='expires_in',
            field=models.IntegerField(null=True),
        ),
    ]
