name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        STRAVA_CLIENT_ID: 1337
        STRAVA_SCOPE: "read_all,profile:read_all,activity:read_all"
        STRAVA_CALLBACK_URI: "https://callback.uri"
        DJANGO_SETTINGS_MODULE: cyclisme.settings.develop
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_TEST }}
      run: |
        pytest
